//Q21

//30 because result is declared outside the function

function myFunction(num1, num2) {
    const result = num1+num2
    return result
  }
  
  const result = myFunction(10, 20)
  myFunction(100, 2)
  console.log(result)

// bang on

